# Generated by Django 3.1.1 on 2020-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now=True)),
                ('event_type', models.IntegerField(choices=[('0', 'OTHER'), ('1', 'BUTTON_PRESS'), ('2', 'JS_ERROR')], default=0)),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('current_url', models.CharField(max_length=256)),
                ('event_meta', models.CharField(max_length=1024)),
                ('session_meta', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
