# Generated by Django 3.1.1 on 2020-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendevent',
            name='event_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='frontendevent',
            name='session_meta',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
