# Generated by Django 3.1.1 on 2020-09-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200915_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
