image: python:latest

stages:
  - test

before_script:
  - git fetch
  - git merge origin master --ff-only
  - python -V
  - pip install -r requirements.txt

test_mr:
  stage: test
  script:
    - sh run-coverage.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    paths:
      - htmlcov/
    expire_in: 2 week

test_master:
  stage: test
  script:
    - sh run-coverage.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  artifacts:
    paths:
      - htmlcov/
    expire_in: 52 weeks