image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: ci

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  script:
    - cd workoutapp
    - python manage.py migrate
    - coverage erase
    - coverage run manage.py test
    - coverage run --append -m unittest weather_service.gateway.weather_gateway_test # Note this is a dirty but needed hack right now
    - coverage report
  only:
    - merge_requests