# Generated by Django 3.1.1 on 2020-09-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200917_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fitcoins',
            field=models.IntegerField(default=0),
        ),
    ]
