# Generated by Django 3.1.1 on 2020-09-11 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200911_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='BirthYear',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
