# Generated by Django 3.1.1 on 2020-09-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200920_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
    ]
