# Generated by Django 3.1.1 on 2020-09-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200920_2154'),
        ('user', '0004_follow'),
    ]

    operations = [
    ]
