# Generated by Django 3.1.1 on 2020-09-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20200921_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='createdAt',
            new_name='CreatedAt',
        ),
    ]
