# Generated by Django 3.1.1 on 2020-10-04 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20200929_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to=settings.AUTH_USER_MODEL)),
                ('ToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
