# Generated by Django 3.1.1 on 2020-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201004_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(),
        ),
    ]
