# Generated by Django 3.1.1 on 2020-10-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userinfo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
