# Generated by Django 3.1.1 on 2020-10-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201018_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
