# Generated by Django 3.1.1 on 2020-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20201018_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cover_image',
            field=models.CharField(default='https://cultivatedculture.com/wp-content/uploads/2019/05/Chromatic-LinkedIn-Cover-Photo-Background.png', max_length=250),
        ),
    ]
