# Generated by Django 3.1.1 on 2020-10-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userinfo_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='image',
            new_name='profile_image',
        ),
    ]
