# Generated by Django 3.1.1 on 2020-10-30 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20201024_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
