# Generated by Django 3.0.6 on 2020-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20201031_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
