# Generated by Django 3.1.1 on 2020-09-11 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Message',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Image',
            field=models.CharField(default='https://www.vhv.rs/dpng/d/256-2569650_men-profile-icon-png-image-free-download-searchpng.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.equipment'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Image',
            field=models.CharField(default='https://www.vhv.rs/dpng/d/256-2569650_men-profile-icon-png-image-free-download-searchpng.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='Unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.category'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='CreatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Image',
            field=models.CharField(default='https://www.vhv.rs/dpng/d/256-2569650_men-profile-icon-png-image-free-download-searchpng.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutmanager',
            name='Exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutmanager',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutmanager',
            name='Reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutmanager',
            name='Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.unittype'),
        ),
    ]
