# Generated by Django 3.1.1 on 2020-09-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20200911_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='Equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.equipment'),
        ),
    ]
