# Generated by Django 3.1.1 on 2020-09-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20200929_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
