# Generated by Django 3.1.1 on 2020-09-30 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0006_auto_20200929_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='Dislikes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='Likes',
        ),
        migrations.CreateModel(
            name='WorkoutRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmittedAt', models.DateTimeField(auto_now=True)),
                ('Rating', models.IntegerField(choices=[('+1', 'LIKE'), ('-1', 'DISLIKE')])),
                ('Exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('Judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmittedAt', models.DateTimeField(auto_now=True)),
                ('Rating', models.IntegerField(choices=[('+1', 'LIKE'), ('-1', 'DISLIKE')])),
                ('Exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('Judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
