# Generated by Django 3.1.1 on 2020-09-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20200930_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutrating',
            name='Exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='Dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutrating',
            name='Workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='Rating',
            field=models.IntegerField(choices=[('+1', 'LIKE'), ('*0', 'IDK'), ('-1', 'DISLIKE')], default=0),
        ),
        migrations.AlterField(
            model_name='workoutrating',
            name='Rating',
            field=models.IntegerField(choices=[('+1', 'LIKE'), ('*0', 'IDK'), ('-1', 'DISLIKE')]),
        ),
    ]
