# Generated by Django 3.1.1 on 2020-09-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20200930_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutrating',
            name='Workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
    ]
