# Generated by Django 3.1.1 on 2020-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_auto_20200930_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Has_Disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Has_Liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Has_Disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Has_Liked',
            field=models.BooleanField(default=False),
        ),
    ]
