# Generated by Django 3.1.1 on 2020-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_remove_workoutmanager_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='CreatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
