# Generated by Django 3.1.1 on 2020-10-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_auto_20201003_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='CreatedAt',
        ),
    ]
