# Generated by Django 3.1.1 on 2020-10-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0015_workout_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutrating',
            name='Rating',
            field=models.IntegerField(choices=[('+1', 'LIKE'), ('*0', 'IDK'), ('-1', 'DISLIKE')], default=0),
        ),
        migrations.AlterField(
            model_name='workoutrating',
            name='Workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
    ]
