# Generated by Django 3.1.1 on 2020-10-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0016_auto_20201003_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='short_description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
