# Generated by Django 3.1.1 on 2020-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0019_remove_workout_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='CreatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='time_passed',
            field=models.CharField(default='1 Day ago', max_length=40),
        ),
    ]
