# Generated by Django 3.1.1 on 2020-10-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0021_auto_20201004_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='CreatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
