# Generated by Django 3.1.1 on 2020-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0022_exercise_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='time_passed',
            field=models.CharField(default='1 Day ago', max_length=40),
        ),
    ]
