# Generated by Django 3.1.1 on 2020-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0024_favouriteexercise_favouriteworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='has_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
